"""Migrations

Revision ID: 105c9b651612
Revises: 
Create Date: 2022-12-03 19:48:20.648610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105c9b651612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deckmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('texas', name='gametypeenum'), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('chips_to_join', sa.Integer(), nullable=True),
    sa.Column('small_blind', sa.Integer(), nullable=True),
    sa.Column('big_blind', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roundmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('preflop', 'flop', 'river', 'turn', 'showdown', name='roundtypeenum'), nullable=True),
    sa.Column('round_ended', sa.Boolean(), nullable=True),
    sa.Column('rounds_played', sa.Integer(), nullable=True),
    sa.Column('all_played', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usermodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cardmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('suit', sa.String(), nullable=True),
    sa.Column('position', sa.Enum('deck', 'player', 'table', name='cardpositionenum'), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deckmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('players_connected', sa.Integer(), nullable=True),
    sa.Column('dealer_position', sa.Integer(), nullable=True),
    sa.Column('small_blind_position', sa.Integer(), nullable=True),
    sa.Column('big_blind_position', sa.Integer(), nullable=True),
    sa.Column('current_player', sa.Integer(), nullable=True),
    sa.Column('last_player', sa.Integer(), nullable=True),
    sa.Column('last_player_action', sa.Enum('unknown', 'fold', 'call', 'bet', 'up', 'allin', name='playeractionenum'), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['gamemodel.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['roundmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playermodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_chips', sa.Integer(), nullable=True),
    sa.Column('in_game_order', sa.Integer(), nullable=True),
    sa.Column('last_bet', sa.Integer(), nullable=True),
    sa.Column('round_bet', sa.Integer(), nullable=True),
    sa.Column('is_allin', sa.Boolean(), nullable=True),
    sa.Column('is_folded', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessionmodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playermodel')
    op.drop_table('sessionmodel')
    op.drop_table('cardmodel')
    op.drop_table('usermodel')
    op.drop_table('roundmodel')
    op.drop_table('gamemodel')
    op.drop_table('deckmodel')
    # ### end Alembic commands ###
