"""Migrations

Revision ID: 4f5fd74cb5ff
Revises: 105c9b651612
Create Date: 2022-12-06 19:54:10.517123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5fd74cb5ff'
down_revision = '105c9b651612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionmodel', sa.Column('max_bet', sa.Integer(), nullable=True))
    op.drop_column('sessionmodel', 'dealer_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionmodel', sa.Column('dealer_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sessionmodel', 'max_bet')
    # ### end Alembic commands ###
